version: "3.7"

services:
  postgres-db:
    build: postgres/.
    container_name: db-container 
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword1234
      - PGPASSWORD=mysecretpassword1234
      - POSTGRES_DB=testdb
      - DATABASE_HOST=localhost
      - DB_EXTENSION=pg_trgm
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
  #    - db-data:/var/lib/postgresql/data
  csweb:
    ports:
      - "80:80"
    build:
      context: pleasanter/.
      args:
      # バージョンを指定
      # 
          - GIT_HASH=cea284d8c57f4794da821c76d5676d0078b30ae0
#    volumes:
#      - csweb-data:/home/Pleasanter.NetCore

#volumes:
#   csweb-data:
#     driver: local
#   db-data:
#     driver: local
